name: Comment on PR
author: Patrick Easters <patrick@patrickeasters.com>
description: Leaves a comment on PR during a pull_request event
branding:
  icon: 'message-square'
  color: 'blue'
inputs:
  msg:
    description: Comment's message
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.msg }}
